{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-reactablefmtr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/reactablefmtr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/reactablefmtr/reactablefmtr_{{ version }}.tar.gz
  sha256: 24ddff264ae3e0cb902c53b87a629eb9d3e1e06cb070fa9cd04a0755912406e5

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-htmltools
    - r-htmlwidgets >=1.5.3
    - r-magrittr
    - r-purrr
    - r-reactable >=0.2.0
    - r-sass >=0.4.0
    - r-shiny
    - r-stringr >=1.4.0
    - r-tippy >=0.1.0
    - r-webshot
  run:
    - r-base
    - r-dplyr
    - r-htmltools
    - r-htmlwidgets >=1.5.3
    - r-magrittr
    - r-purrr
    - r-reactable >=0.2.0
    - r-sass >=0.4.0
    - r-shiny
    - r-stringr >=1.4.0
    - r-tippy >=0.1.0
    - r-webshot

test:
  commands:
    - $R -e "library('reactablefmtr')"           # [not win]
    - "\"%R%\" -e \"library('reactablefmtr')\""  # [win]

about:
  home: https://kcuilla.github.io/reactablefmtr/, https://github.com/kcuilla/reactablefmtr
  license: MIT
  summary: Enhance the styling of interactive reactable tables with easy-to-use and highly-customizable functions. Apply conditional formatting to cells with data bars, color scales, and icon sets. Utilize custom table themes inspired by popular websites and bootstrap themes. Increase the portability and reproducibility
    of reactable tables by embedding images from the web directly into cells. Save the final table output as a static image or interactive file (note this feature requires the 'webshot2' package which can be downloaded from <https://github.com/rstudio/webshot2>).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
